"""Seed the database with sample Turkish recipes for development/demo."""

import asyncio
from database import get_db, init_db, upsert_category, upsert_recipe, upsert_ingredients, upsert_steps

SAMPLE_CATEGORIES = [
    {"name": "Ana Yemek", "slug": "ana-yemek"},
    {"name": "Çorba", "slug": "corba"},
    {"name": "Tatlı", "slug": "tatli"},
    {"name": "Salata", "slug": "salata"},
    {"name": "Aperatif", "slug": "aperatif"},
    {"name": "İçecek", "slug": "icecek"},
    {"name": "Kahvaltı", "slug": "kahvalti"},
    {"name": "Hamur İşi", "slug": "hamur-isi"},
]

SAMPLE_RECIPES = [
    {
        "id": "r-mercimek-corbasi",
        "title": "Mercimek Çorbası",
        "description": "Klasik Türk mercimek çorbası, kırmızı mercimek ile yapılan besleyici ve lezzetli bir çorba.",
        "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
        "category_slug": "corba",
        "total_time": "35 min",
        "difficulty": "easy",
        "servings": 6,
        "ingredients": [
            {"name": "Kırmızı mercimek", "amount": "2", "unit": "su bardağı"},
            {"name": "Soğan", "amount": "1", "unit": "adet"},
            {"name": "Havuç", "amount": "1", "unit": "adet"},
            {"name": "Patates", "amount": "1", "unit": "adet"},
            {"name": "Tereyağı", "amount": "2", "unit": "yemek kaşığı"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Karabiber", "amount": None, "unit": None},
            {"name": "Pul biber", "amount": "1", "unit": "tatlı kaşığı"},
            {"name": "Limon", "amount": "1", "unit": "adet"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Mercimekleri yıkayın ve süzün."},
            {"step_number": 2, "instruction": "Soğanı, havucu ve patatesi küçük küçük doğrayın."},
            {"step_number": 3, "instruction": "Tencerede tereyağını eritin, soğanları kavurun."},
            {"step_number": 4, "instruction": "Havuç ve patatesi ekleyip 2-3 dakika kavurun."},
            {"step_number": 5, "instruction": "Mercimekleri ve 6 su bardağı su ekleyin. Kaynamaya bırakın."},
            {"step_number": 6, "instruction": "Kısık ateşte 25 dakika pişirin."},
            {"step_number": 7, "instruction": "Blender ile pürüzsüz hale getirin. Tuz ve baharatları ekleyin."},
            {"step_number": 8, "instruction": "Limon sıkarak servis edin."},
        ],
    },
    {
        "id": "r-tavuk-sote",
        "title": "Tavuk Sote",
        "description": "Sebzeli tavuk sote, pratik ve lezzetli bir ana yemek.",
        "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800",
        "category_slug": "ana-yemek",
        "total_time": "45 min",
        "difficulty": "easy",
        "servings": 4,
        "ingredients": [
            {"name": "Tavuk göğsü", "amount": "500", "unit": "g"},
            {"name": "Soğan", "amount": "2", "unit": "adet"},
            {"name": "Yeşil biber", "amount": "3", "unit": "adet"},
            {"name": "Domates", "amount": "3", "unit": "adet"},
            {"name": "Zeytinyağı", "amount": "3", "unit": "yemek kaşığı"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Karabiber", "amount": None, "unit": None},
            {"name": "Pul biber", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Tavukları küp küp doğrayın."},
            {"step_number": 2, "instruction": "Soğanları halka, biberleri doğrayın."},
            {"step_number": 3, "instruction": "Zeytinyağında soğanları kavurun."},
            {"step_number": 4, "instruction": "Tavukları ekleyip suyunu çekene kadar kavurun."},
            {"step_number": 5, "instruction": "Biberleri ve doğranmış domatesleri ekleyin."},
            {"step_number": 6, "instruction": "Kısık ateşte 20 dakika pişirin. Baharatları ekleyin."},
        ],
    },
    {
        "id": "r-kisir",
        "title": "Kısır",
        "description": "Bulgurdan yapılan geleneksel Türk salatası, bol limonlu ve baharatlı.",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
        "category_slug": "salata",
        "total_time": "30 min",
        "difficulty": "easy",
        "servings": 8,
        "ingredients": [
            {"name": "İnce bulgur", "amount": "2", "unit": "su bardağı"},
            {"name": "Domates salçası", "amount": "2", "unit": "yemek kaşığı"},
            {"name": "Biber salçası", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Limon suyu", "amount": "3", "unit": "adet"},
            {"name": "Zeytinyağı", "amount": "4", "unit": "yemek kaşığı"},
            {"name": "Yeşil soğan", "amount": "1", "unit": "demet"},
            {"name": "Maydanoz", "amount": "1", "unit": "demet"},
            {"name": "Nane", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Domates", "amount": "2", "unit": "adet"},
            {"name": "Salatalık", "amount": "1", "unit": "adet"},
            {"name": "Tuz", "amount": None, "unit": None},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Bulguru bir kaseye alın, üzerine kaynar su dökün. Kapağını kapatıp 15 dakika şişmeye bırakın."},
            {"step_number": 2, "instruction": "Salçaları, zeytinyağını ve limon suyunu bulgura ekleyip karıştırın."},
            {"step_number": 3, "instruction": "Yeşil soğan, maydanoz, domates ve salatalığı ince ince doğrayın."},
            {"step_number": 4, "instruction": "Tüm malzemeleri bulgura ekleyin. Nane ve tuzu ilave edip karıştırın."},
            {"step_number": 5, "instruction": "Buzdolabında 30 dakika dinlendirip servis edin."},
        ],
    },
    {
        "id": "r-menemen",
        "title": "Menemen",
        "description": "Domates, biber ve yumurta ile yapılan klasik Türk kahvaltılığı.",
        "image_url": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800",
        "category_slug": "kahvalti",
        "total_time": "15 min",
        "difficulty": "easy",
        "servings": 2,
        "ingredients": [
            {"name": "Yumurta", "amount": "4", "unit": "adet"},
            {"name": "Domates", "amount": "3", "unit": "adet"},
            {"name": "Yeşil biber", "amount": "2", "unit": "adet"},
            {"name": "Soğan", "amount": "1", "unit": "adet"},
            {"name": "Tereyağı", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Karabiber", "amount": None, "unit": None},
            {"name": "Pul biber", "amount": None, "unit": None},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Soğanı ve biberleri doğrayın. Domatesleri rendeleyin."},
            {"step_number": 2, "instruction": "Tavada tereyağını eritin, soğan ve biberleri kavurun."},
            {"step_number": 3, "instruction": "Domatesleri ekleyip suyunu çekene kadar pişirin."},
            {"step_number": 4, "instruction": "Yumurtaları kırın, hafifçe karıştırıp 2 dakika pişirin."},
        ],
    },
    {
        "id": "r-icli-kofte",
        "title": "İçli Köfte",
        "description": "Bulgur hamurunun içine kıymalı harç konularak yapılan geleneksel lezzet.",
        "image_url": "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800",
        "category_slug": "aperatif",
        "total_time": "90 min",
        "difficulty": "difficult",
        "servings": 6,
        "ingredients": [
            {"name": "İnce bulgur", "amount": "3", "unit": "su bardağı"},
            {"name": "İrmik", "amount": "1", "unit": "su bardağı"},
            {"name": "Kıyma", "amount": "300", "unit": "g"},
            {"name": "Soğan", "amount": "3", "unit": "adet"},
            {"name": "Ceviz", "amount": "1", "unit": "su bardağı"},
            {"name": "Maydanoz", "amount": "1", "unit": "demet"},
            {"name": "Biber salçası", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Karabiber", "amount": None, "unit": None},
            {"name": "Kimyon", "amount": "1", "unit": "tatlı kaşığı"},
            {"name": "Pul biber", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "İç harç: Soğanları kavurun, kıymayı ekleyin. Ceviz, maydanoz, baharat ekleyin."},
            {"step_number": 2, "instruction": "Dış hamur: Bulgur ve irmiği yoğurun, biber salçası ekleyin."},
            {"step_number": 3, "instruction": "Hamurdan ceviz büyüklüğünde parçalar koparın, içini oyun."},
            {"step_number": 4, "instruction": "İç harcı doldurun, ağzını kapatıp şekil verin."},
            {"step_number": 5, "instruction": "Kaynar suda 5-7 dakika haşlayın veya kızgın yağda kızartın."},
        ],
    },
    {
        "id": "r-baklava",
        "title": "Baklava",
        "description": "İnce yufkalar arasında ceviz veya fıstık ile yapılan geleneksel Türk tatlısı.",
        "image_url": "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800",
        "category_slug": "tatli",
        "total_time": "120 min",
        "difficulty": "difficult",
        "servings": 12,
        "ingredients": [
            {"name": "Yufka", "amount": "500", "unit": "g"},
            {"name": "Tereyağı", "amount": "250", "unit": "g"},
            {"name": "Ceviz", "amount": "300", "unit": "g"},
            {"name": "Şeker", "amount": "3", "unit": "su bardağı"},
            {"name": "Su", "amount": "2.5", "unit": "su bardağı"},
            {"name": "Limon suyu", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Şerbeti hazırlayın: Şeker ve suyu kaynatın, limon suyu ekleyin. Soğumaya bırakın."},
            {"step_number": 2, "instruction": "Cevizleri iri iri kırın."},
            {"step_number": 3, "instruction": "Yufkaları tepsiye sererek aralarına tereyağı sürün."},
            {"step_number": 4, "instruction": "Her 3-4 yufkada bir ceviz serpin."},
            {"step_number": 5, "instruction": "Üzerine erimiş tereyağı gezdirin. Dilimleyin."},
            {"step_number": 6, "instruction": "170°C fırında 45-50 dakika altın rengi olana kadar pişirin."},
            {"step_number": 7, "instruction": "Sıcak baklavanın üzerine soğuk şerbeti dökün. 2 saat dinlendirin."},
        ],
    },
    {
        "id": "r-pilav",
        "title": "Tereyağlı Pirinç Pilavı",
        "description": "Tane tane, tereyağlı klasik Türk pilavı.",
        "image_url": "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800",
        "category_slug": "ana-yemek",
        "total_time": "40 min",
        "difficulty": "medium",
        "servings": 4,
        "ingredients": [
            {"name": "Pirinç", "amount": "2", "unit": "su bardağı"},
            {"name": "Tereyağı", "amount": "2", "unit": "yemek kaşığı"},
            {"name": "Şehriye", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Tavuk suyu", "amount": "3", "unit": "su bardağı"},
            {"name": "Tuz", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Pirinci ılık suda 30 dakika bekletin, süzün."},
            {"step_number": 2, "instruction": "Tereyağında şehriyeleri kavurun."},
            {"step_number": 3, "instruction": "Pirinci ekleyip 2 dakika kavurun."},
            {"step_number": 4, "instruction": "Sıcak tavuk suyunu ve tuzu ekleyin."},
            {"step_number": 5, "instruction": "Kapağını kapatıp kısık ateşte 15-18 dakika pişirin."},
            {"step_number": 6, "instruction": "Ocaktan alın, havlu koyup 10 dakika dinlendirin."},
        ],
    },
    {
        "id": "r-yaprak-sarma",
        "title": "Yaprak Sarma (Zeytinyağlı)",
        "description": "Asma yaprağına sarılmış pirinçli, zeytinyağlı soğuk sarma.",
        "image_url": "https://images.unsplash.com/photo-1600803907087-f56d462fd26b?w=800",
        "category_slug": "aperatif",
        "total_time": "90 min",
        "difficulty": "medium",
        "servings": 6,
        "ingredients": [
            {"name": "Asma yaprağı", "amount": "50", "unit": "adet"},
            {"name": "Pirinç", "amount": "1.5", "unit": "su bardağı"},
            {"name": "Soğan", "amount": "3", "unit": "adet"},
            {"name": "Zeytinyağı", "amount": "1", "unit": "çay bardağı"},
            {"name": "Domates salçası", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Nane", "amount": "1", "unit": "yemek kaşığı"},
            {"name": "Tarçın", "amount": "1", "unit": "tatlı kaşığı"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Limon suyu", "amount": "2", "unit": "yemek kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Soğanları ince ince doğrayıp zeytinyağında kavurun."},
            {"step_number": 2, "instruction": "Pirinci ekleyip 5 dakika kavurun. Salça, baharat ve tuzu ekleyin."},
            {"step_number": 3, "instruction": "Asma yapraklarını haşlayıp süzün."},
            {"step_number": 4, "instruction": "Her yaprağa bir tatlı kaşığı harç koyup sıkıca sarın."},
            {"step_number": 5, "instruction": "Tencereye dizin, üzerine su, limon suyu ve zeytinyağı ekleyin."},
            {"step_number": 6, "instruction": "Kısık ateşte 45 dakika pişirin. Soğuduktan sonra servis edin."},
        ],
    },
    {
        "id": "r-ayran",
        "title": "Ayran",
        "description": "Yoğurt, su ve tuz ile yapılan geleneksel Türk içeceği.",
        "image_url": "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
        "category_slug": "icecek",
        "total_time": "5 min",
        "difficulty": "easy",
        "servings": 4,
        "ingredients": [
            {"name": "Yoğurt", "amount": "2", "unit": "su bardağı"},
            {"name": "Su", "amount": "2", "unit": "su bardağı"},
            {"name": "Tuz", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Yoğurdu bir kaseye alın."},
            {"step_number": 2, "instruction": "Soğuk suyu ve tuzu ekleyin."},
            {"step_number": 3, "instruction": "Mikser veya çırpıcı ile köpürtün."},
            {"step_number": 4, "instruction": "Soğuk servis edin."},
        ],
    },
    {
        "id": "r-su-boregi",
        "title": "Su Böreği",
        "description": "Haşlanmış yufka katları arasında peynirli, geleneksel Türk böreği.",
        "image_url": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
        "category_slug": "hamur-isi",
        "total_time": "60 min",
        "difficulty": "medium",
        "servings": 8,
        "ingredients": [
            {"name": "Yufka", "amount": "6", "unit": "adet"},
            {"name": "Beyaz peynir", "amount": "400", "unit": "g"},
            {"name": "Yumurta", "amount": "3", "unit": "adet"},
            {"name": "Maydanoz", "amount": "1", "unit": "demet"},
            {"name": "Süt", "amount": "1", "unit": "su bardağı"},
            {"name": "Zeytinyağı", "amount": "1", "unit": "çay bardağı"},
            {"name": "Tereyağı", "amount": "100", "unit": "g"},
            {"name": "Tuz", "amount": None, "unit": None},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Peyniri ufalayın, yumurta ve maydanoz ile karıştırın."},
            {"step_number": 2, "instruction": "Büyük bir tencerede su kaynatın, tuz ekleyin."},
            {"step_number": 3, "instruction": "Yufkaları teker teker kaynar suda 1 dakika haşlayın, buzlu suya alın."},
            {"step_number": 4, "instruction": "Tepsiye yağ sürün. Haşlanmış yufkaları sererek aralarına peynir harcı koyun."},
            {"step_number": 5, "instruction": "Üzerine süt, yumurta ve erimiş tereyağı karışımını dökün."},
            {"step_number": 6, "instruction": "180°C fırında 35-40 dakika altın rengi olana kadar pişirin."},
        ],
    },
    {
        "id": "r-imam-bayildi",
        "title": "İmam Bayıldı",
        "description": "Zeytinyağlı, soğan ve domates dolgulu patlıcan yemeği.",
        "image_url": "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800",
        "category_slug": "ana-yemek",
        "total_time": "60 min",
        "difficulty": "medium",
        "servings": 4,
        "ingredients": [
            {"name": "Patlıcan", "amount": "4", "unit": "adet"},
            {"name": "Soğan", "amount": "3", "unit": "adet"},
            {"name": "Domates", "amount": "4", "unit": "adet"},
            {"name": "Sarımsak", "amount": "4", "unit": "diş"},
            {"name": "Zeytinyağı", "amount": "1", "unit": "çay bardağı"},
            {"name": "Maydanoz", "amount": "1", "unit": "demet"},
            {"name": "Tuz", "amount": None, "unit": None},
            {"name": "Şeker", "amount": "1", "unit": "tatlı kaşığı"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Patlıcanları alacalı soyun, ortadan yarın, tuzlu suda bekletin."},
            {"step_number": 2, "instruction": "Soğanları ince doğrayıp zeytinyağında kavurun."},
            {"step_number": 3, "instruction": "Domates ve sarımsağı ekleyip 10 dakika pişirin."},
            {"step_number": 4, "instruction": "Patlıcanları tepsiye dizin, üzerlerine harcı doldurun."},
            {"step_number": 5, "instruction": "Yarım bardak sıcak su ekleyin."},
            {"step_number": 6, "instruction": "180°C fırında 40 dakika pişirin. Soğuk servis edin."},
        ],
    },
    {
        "id": "r-sutlac",
        "title": "Sütlaç",
        "description": "Fırında kızarmış geleneksel Türk pirinç sütlacı.",
        "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
        "category_slug": "tatli",
        "total_time": "50 min",
        "difficulty": "easy",
        "servings": 6,
        "ingredients": [
            {"name": "Pirinç", "amount": "0.5", "unit": "su bardağı"},
            {"name": "Süt", "amount": "1", "unit": "litre"},
            {"name": "Şeker", "amount": "1", "unit": "su bardağı"},
            {"name": "Nişasta", "amount": "2", "unit": "yemek kaşığı"},
            {"name": "Vanilya", "amount": "1", "unit": "paket"},
        ],
        "steps": [
            {"step_number": 1, "instruction": "Pirinci yıkayıp bir bardak su ile yumuşayana kadar haşlayın."},
            {"step_number": 2, "instruction": "Sütü ekleyip karıştırarak kaynatın."},
            {"step_number": 3, "instruction": "Şekeri ve soğuk sütte eritilmiş nişastayı ekleyin."},
            {"step_number": 4, "instruction": "Kıvam alana kadar karıştırarak pişirin. Vanilya ekleyin."},
            {"step_number": 5, "instruction": "Kaselere bölün, 200°C fırında üzeri kızarana kadar pişirin."},
            {"step_number": 6, "instruction": "Soğutup buzdolabında dinlendirin."},
        ],
    },
]


async def seed():
    await init_db()
    db = await get_db()
    try:
        # Insert categories
        cat_map = {}
        for cat in SAMPLE_CATEGORIES:
            cat_id = await upsert_category(db, cat["name"], cat["slug"])
            cat_map[cat["slug"]] = cat_id

        # Insert recipes
        for r in SAMPLE_RECIPES:
            cat_id = cat_map.get(r["category_slug"])
            await upsert_recipe(db, {
                "id": r["id"],
                "title": r["title"],
                "description": r["description"],
                "image_url": r["image_url"],
                "image_local": None,
                "category_id": cat_id,
                "total_time": r["total_time"],
                "difficulty": r["difficulty"],
                "servings": r["servings"],
                "source_url": f"https://cookidoo.com.tr/recipes/recipe/tr-TR/{r['id']}",
            })
            await upsert_ingredients(db, r["id"], r["ingredients"])
            await upsert_steps(db, r["id"], r["steps"])

        await db.commit()
        print(f"Seeded {len(SAMPLE_CATEGORIES)} categories and {len(SAMPLE_RECIPES)} recipes.")
    finally:
        await db.close()


if __name__ == "__main__":
    asyncio.run(seed())
